server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: order-service
          uri: http://orderservice:8081
          predicates:
            - Path=/orders/**

        - id: product-service
          uri: http://productservice:8082
          predicates:
            - Path=/products/**

        - id: inventory-service
          uri: http://inventoryservice:8080
          predicates:
            - Path=/inventory/**

        - id: customer-service
          uri: http://localhost:3000
          predicates:
            - Path=/customers/**
