global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'PRODUCT-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'INVENTORY-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8085' ]